#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Apr 27 16:04:31 2014

import wx
import cfg
from MainFrame import MainFrame

class XRDMapGridApp(wx.App):
    def OnInit(self):
        #read global configuration variables
        cfg.read_config()
        #create main window
        frame = MainFrame(None, -1, "XRD MapGrid")
        self.SetTopWindow(frame)
        frame.Show()
        return True

if __name__ == "__main__":
    app = XRDMapGridApp(False)
    wx.InitAllImageHandlers()
    app.MainLoop()
