# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Apr 27 16:04:31 2014

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class AxesGridDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AxesGridDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX
        wx.Dialog.__init__(self, *args, **kwds)
        self.stNbRows = wx.StaticText(self, -1, "Number of rows")
        self.scNbRows = wx.SpinCtrl(self, -1, "1", min=1, max=10)
        self.stNbColumns = wx.StaticText(self, -1, "Number of columns")
        self.scNbColumns = wx.SpinCtrl(self, -1, "1", min=1, max=10)
        self.bCancel = wx.Button(self, wx.ID_CANCEL, "Cancel")
        self.bOK = wx.Button(self, wx.ID_OK, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AxesGridDialog.__set_properties
        self.SetTitle("Dialog")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AxesGridDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(2, 2, 1, 1)
        grid_sizer_1.Add(self.stNbRows, 0, 0, 0)
        grid_sizer_1.Add(self.scNbRows, 0, 0, 0)
        grid_sizer_1.Add(self.stNbColumns, 0, 0, 0)
        grid_sizer_1.Add(self.scNbColumns, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_2.Add(self.bCancel, 0, wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_BOTTOM, 10)
        sizer_2.Add(self.bOK, 0, wx.LEFT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_BOTTOM, 10)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class AxesGridDialog
