# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Apr 27 23:14:51 2014

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class AxesPreferencesDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AxesPreferencesDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.stAxesLimits = wx.StaticText(self, -1, "Axes limits")
        self.label_4 = wx.StaticText(self, -1, "X axis")
        self.label_2 = wx.StaticText(self, -1, "min:")
        self.text_ctrl_4 = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, "max:")
        self.text_ctrl_5 = wx.TextCtrl(self, -1, "")
        self.label_5 = wx.StaticText(self, -1, "Y axis")
        self.label_6 = wx.StaticText(self, -1, "min:")
        self.text_ctrl_6 = wx.TextCtrl(self, -1, "")
        self.label_7 = wx.StaticText(self, -1, "max:")
        self.text_ctrl_7 = wx.TextCtrl(self, -1, "")
        self.label_1 = wx.StaticText(self, -1, "Axes ratio")
        self.slider_1 = wx.Slider(self, -1, 1, 1, 100, style=wx.SL_HORIZONTAL | wx.SL_AUTOTICKS | wx.SL_LABELS | wx.SL_RIGHT)
        self.bCancel = wx.Button(self, wx.ID_CANCEL, "Cancel")
        self.bApply = wx.Button(self, wx.ID_APPLY, "Apply")
        self.bOK = wx.Button(self, wx.ID_OK, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AxesPreferencesDialog.__set_properties
        self.SetTitle("Axes settings")
        self.bOK.SetFocus()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AxesPreferencesDialog.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10.Add(self.stAxesLimits, 0, wx.EXPAND, 0)
        sizer_14.Add(self.label_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_16.Add(self.label_2, 0, wx.ALIGN_BOTTOM, 0)
        sizer_16.Add(self.text_ctrl_4, 0, 0, 0)
        sizer_16.Add(self.label_3, 0, wx.ALIGN_BOTTOM, 0)
        sizer_16.Add(self.text_ctrl_5, 0, 0, 0)
        sizer_14.Add(sizer_16, 0, wx.LEFT | wx.TOP | wx.EXPAND, 5)
        sizer_13.Add(sizer_14, 0, wx.EXPAND, 0)
        sizer_15.Add(self.label_5, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_17.Add(self.label_6, 0, wx.ALIGN_BOTTOM, 0)
        sizer_17.Add(self.text_ctrl_6, 0, 0, 0)
        sizer_17.Add(self.label_7, 0, wx.ALIGN_BOTTOM, 0)
        sizer_17.Add(self.text_ctrl_7, 0, 0, 0)
        sizer_15.Add(sizer_17, 0, wx.LEFT | wx.TOP | wx.EXPAND, 5)
        sizer_13.Add(sizer_15, 0, wx.EXPAND, 0)
        sizer_10.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_6.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_7.Add(self.label_1, 0, wx.ALIGN_BOTTOM, 0)
        sizer_7.Add(self.slider_1, 1, wx.LEFT | wx.RIGHT | wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(sizer_7, 0, wx.BOTTOM | wx.EXPAND, 20)
        sizer_5.Add(self.bCancel, 0, wx.LEFT | wx.ALIGN_RIGHT | wx.ALIGN_BOTTOM, 10)
        sizer_5.Add(self.bApply, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5.Add(self.bOK, 0, wx.RIGHT | wx.ALIGN_BOTTOM, 10)
        sizer_4.Add(sizer_5, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

# end of class AxesPreferencesDialog
