# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Apr 27 16:04:31 2014

import wx
from AxesGridDialog import AxesGridDialog

# begin wxGlade: dependencies
from MplPanel import MplPanel
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.menubar = wx.MenuBar()
        self.File = wx.Menu()
        self.Save = wx.MenuItem(self.File, wx.ID_SAVE, "&Save", "Have current figure", wx.ITEM_NORMAL)
        self.File.AppendItem(self.Save)
        self.Exit = wx.MenuItem(self.File, wx.ID_EXIT, "E&xit", "Terminate the program", wx.ITEM_NORMAL)
        self.File.AppendItem(self.Exit)
        self.menubar.Append(self.File, "&File")
        self.Options = wx.Menu()
        self.SetGrid = wx.MenuItem(self.Options, wx.ID_PROPERTIES, "Set grid", "Defined the size of the grid grid", wx.ITEM_NORMAL)
        self.Options.AppendItem(self.SetGrid)
        self.menubar.Append(self.Options, "&Options")
        self.Help = wx.Menu()
        self.About = wx.MenuItem(self.Help, wx.ID_ABOUT, "&About", "Information about this program", wx.ITEM_NORMAL)
        self.Help.AppendItem(self.About)
        self.menubar.Append(self.Help, "&Help")
        self.SetMenuBar(self.menubar)
        # Menu Bar end
        self.mplPanel = MplPanel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.onSave, self.Save)
        self.Bind(wx.EVT_MENU, self.onExit, self.Exit)
        self.Bind(wx.EVT_MENU, self.onSetGrid, self.SetGrid)
        self.Bind(wx.EVT_MENU, self.onAbout, self.About)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Main Window")
        self.SetSize((650, 490))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.mplPanel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer)
        self.Layout()
        # end wxGlade
        
    def onAbout(self, event):  # wxGlade: MainFrame.<event_handler>
        #Create a message dialog box
        dlg = wx.MessageDialog(self, "XRD MapGrid v0.1\nAuthor: Viktor Kopp", "XRD", wx.OK)
        dlg.ShowModal()
        dlg.Destroy()

    def onExit(self, event):  # wxGlade: MainFrame.<event_handler>
        self.Close(True)

    def onSetGrid(self, event):  # wxGlade: MainFrame.<event_handler>
        dialog = AxesGridDialog(self)
        
        if dialog.ShowModal() == wx.ID_OK:
            nr = int(dialog.scNbRows.GetValue())
            nc = int(dialog.scNbColumns.GetValue())
            self.mplPanel.set_grid(nr, nc)
            print "%s x %s grid has been defined" % (nr, nc)
        
        dialog.Destroy()

    def onSave(self, event):  # wxGlade: MainFrame.<event_handler>
        if self.mplPanel.figure.get_axes():#if there is 
            #split file into base part and extension part
            base = "figure"
            
            #propose to save file with the same base as input file but with qfit extension
            dlg = wx.FileDialog(self, "Save image", "", base + '.eps',
                            "*.*", wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT)
            if dlg.ShowModal() == wx.ID_OK:
                # save content in the file
                path = dlg.GetPath()
                self.mplPanel.figure.savefig(path)
        else:
            #Create a message dialog box
            dlg = wx.MessageDialog(self, "Figure is empty", "Worning", wx.OK)
            dlg.ShowModal()
            dlg.Destroy()

# end of class MainFrame
