# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Apr 27 16:04:31 2014

import wx
from AxesGridDialog import AxesGridDialog

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.button = wx.Button(self, -1, "Show dialog")
        
        # Menu Bar
        self.menubar = wx.MenuBar()
        self.File = wx.Menu()
        self.Close = wx.MenuItem(self.File, wx.ID_CLOSE, "Close", "Close program", wx.ITEM_NORMAL)
        self.File.AppendItem(self.Close)
        self.menubar.Append(self.File, "File")
        self.Help = wx.Menu()
        self.About = wx.MenuItem(self.Help, wx.ID_ABOUT, "About", "Information about this program", wx.ITEM_NORMAL)
        self.Help.AppendItem(self.About)
        self.menubar.Append(self.Help, "Help")
        self.SetMenuBar(self.menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onShowDialog, self.button)
        self.Bind(wx.EVT_MENU, self.onClose, self.Close)
        self.Bind(wx.EVT_MENU, self.onAbout, self.About)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Main Window")
        self.SetSize((640, 480))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.button, 0, wx.ALL | wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer)
        self.Layout()
        # end wxGlade

    def onShowDialog(self, event):  # wxGlade: MainFrame.<event_handler>
        dialog = AxesGridDialog(self)
        
        if dialog.ShowModal() == wx.ID_OK:
            print "%s x %s grid has been defined" % (dialog.scNbRows.GetValue(), dialog.scNbColumns.GetValue())
        
        dialog.Destroy()
        

    def onClose(self, event):  # wxGlade: MainFrame.<event_handler>
        print "Event handler `onClose' not implemented"
        event.Skip()

    def onAbout(self, event):  # wxGlade: MainFrame.<event_handler>
        print "Event handler `onAbout' not implemented"
        event.Skip()

# end of class MainFrame
