# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Apr 27 17:28:49 2014

import wx
from matplotlib.figure import Figure
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class MplPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MplPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        # add matplotlib figure
        self.figure = Figure()
        # add figure to canvas
        self.canvas = FigureCanvas(self, wx.ID_ANY, self.figure)

    def __set_properties(self):
        # begin wxGlade: MplPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MplPanel.__do_layout
        pass
        # end wxGlade

# end of class MplPanel
